name: Release

on:
  push:
    branches: [feat/ton-api]

concurrency:
  group: ${{github.event.repository.name}}

env:
  workspace: ${{vars.WORKSPACE}}
  TF_VAR_project_name: ${{vars.PROJECT_NAME}}
  TF_VAR_aws_region: ${{vars.AWS_REGION}}
  TF_VAR_api_domain: ${{vars.API_DOMAIN}}
  TF_VAR_bucket_states: ${{vars.BUCKET_STATES}}
  AWS_REGION: ${{vars.AWS_REGION}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  Infra:
    name: Infra
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform workspace
        working-directory: .terraform
        run: (terraform workspace new ${{env.workspace}} || true) && terraform workspace select ${{env.workspace}}

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve
